// Mocks generated by Mockito 5.4.4 from annotations
// in bdl_demo/test/features/games/domain/use_cases/get_schedule_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bdl_demo/features/games/domain/entities/game.dart' as _i5;
import 'package:bdl_demo/features/games/domain/repositories/games_repository.dart'
    as _i3;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAsyncValue_0<T> extends _i1.SmartFake implements _i2.AsyncValue<T> {
  _FakeAsyncValue_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GamesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGamesRepository extends _i1.Mock implements _i3.GamesRepository {
  MockGamesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AsyncValue<List<_i5.Game>>> getSchedule(String? teamId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSchedule,
          [teamId],
        ),
        returnValue: _i4.Future<_i2.AsyncValue<List<_i5.Game>>>.value(
            _FakeAsyncValue_0<List<_i5.Game>>(
          this,
          Invocation.method(
            #getSchedule,
            [teamId],
          ),
        )),
      ) as _i4.Future<_i2.AsyncValue<List<_i5.Game>>>);
}
